[versions]
kotlin = "2.2.21"
intellijPlatform = "2.10.5"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
